# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor R package dependencies (renv.lock)
  - package-ecosystem: "github-actions"
    directory: "/" # Location of GitHub Actions workflows
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/" # Location of your Dockerfile
    schedule:
      interval: "weekly"

  # If you use renv for R dependencies, add this section
  - package-ecosystem: "renv"
    directory: "/" # Adjust if your renv.lock is in a subdirectory
    schedule:
      interval: "weekly"
